### ISSUE TITLE
Persistent hostid mismatch error

### ISSUE THREAD

**Issue by p4block** [Pectojin/docker-zfswatcher#1]
Just installed this, enabled web server and went into the Pool Stats tab. Getting this familiar error:

>   Mismatch between pool hostid and system hostid on imported pool. This pool was previously imported into a system with a different hostid, and then was verbatim imported into this system.

The error doesn't show on `zpool status` on the host.

It semi makes sense considering that what it is saying is true and the container doesn't share my host's hostid (afaik)

I'm also using NixOS, which could have interesting consequences.

**Comment by Pectojin** [comment]
I'm afraid I can't replicate the issue. Does the issue on zfsonlinux github apply? https://github.com/zfsonlinux/zfs/issues/9367#issuecomment-536045345

Additionally repo is just my docker-compose/dockerfile for building the image, if the issue happens within ZFS or within the zfswatcher application I can't really do anything to fix it.

**Comment by p4block** [comment]
Thanks for the quick reply. My first reaction was to go and ask if anyone else had the same behavior, I understand that it isn't really a thing to fix here (probably)

I will investigate the linked issue, thanks!

**Comment by Pectojin** [comment]
I got the error today, so I could actually replicate 👍 

It seems like ZFS just writes the hostid into /etc/hostid, so mounting it in fixed the duplication detected. https://github.com/Pectojin/docker-zfswatcher/commit/e016d6fce2490dc0d2a912a5dd21215c9dd4f586

I also regenerated the hostid as explain in the zfsonlinux comment, but I'm really not sure it did anything. Oh and I had to reboot too.
